export const sermonsData = {
  1: {
    id: 1,
    title: "Walking by Faith, Not by Sight",
    preacher: "Pastor Ian Sendegeya",
    date: "2024-01-13",
    duration: "45 min",
    category: "sabbath-worship",
    series: "Living by Faith",
    description: "An inspiring message about trusting God's plan even when we cannot see the way forward.",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    audioUrl: "https://example.com/sermons/audio/walking-by-faith.mp3",
    thumbnail: "/sermon-thumb-1.png",
    speakerPhoto: "/pastor-ian-sendegeya.jpg",
    speakerBio:
      "Lead Pastor at Seventh-day Adventist Church Masaka Town, passionate about youth ministry and evangelism.",
    views: 1250,
    ministry: "Youth Ministry",
    ministrySlug: "youth-ministry",
  },
  2: {
    id: 2,
    title: "The Power of Prayer in Youth",
    preacher: "Pastor Sarah Nambi",
    date: "2024-01-06",
    duration: "35 min",
    category: "youth-services",
    series: "Youth Empowerment",
    description: "Discovering how young people can develop a meaningful prayer life and connect with God.",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    audioUrl: "https://example.com/sermons/audio/power-of-prayer.mp3",
    thumbnail: "/sermon-thumb-2.png",
    speakerPhoto: "/youth-leader-1.jpg",
    speakerBio: "Youth Pastor with a heart for mentoring young people in their spiritual journey.",
    views: 980,
    ministry: "Youth Ministry",
    ministrySlug: "youth-ministry",
  },
  3: {
    id: 3,
    title: "The Three Angels' Messages Today",
    preacher: "Pastor Ian Sendegeya",
    date: "2023-12-30",
    duration: "52 min",
    category: "evangelistic",
    series: "End Time Prophecy",
    description: "Understanding the relevance of Revelation 14 in our modern world and end-time preparation.",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    audioUrl: "https://example.com/sermons/audio/three-angels.mp3",
    thumbnail: "/sermon-thumb-3.png",
    speakerPhoto: "/pastor-ian-sendegeya.jpg",
    speakerBio:
      "Lead Pastor at Seventh-day Adventist Church Masaka Town, passionate about youth ministry and evangelism.",
    views: 1580,
    ministry: "Community Outreach",
    ministrySlug: "community-outreach",
  },
  4: {
    id: 4,
    title: "Sabbath: A Gift of Rest",
    preacher: "Elder David Ssemakula",
    date: "2023-12-23",
    duration: "38 min",
    category: "sabbath-worship",
    series: "Living by Faith",
    description: "Exploring the beauty and blessing of the Sabbath as God's gift to humanity.",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    audioUrl: "https://example.com/sermons/audio/sabbath-gift.mp3",
    thumbnail: "/sermon-thumb-4.png",
    speakerPhoto: "/placeholder.svg?height=100&width=100",
    speakerBio: "Church Elder with decades of experience in Sabbath School ministry.",
    views: 720,
    ministry: "Sabbath School",
    ministrySlug: "sabbath-school",
  },
  5: {
    id: 5,
    title: "Reaching the Lost in Our Community",
    preacher: "Pastor Sarah Nambi",
    date: "2023-12-16",
    duration: "41 min",
    category: "evangelistic",
    series: "Mission Outreach",
    description: "Practical ways to share God's love and the gospel message with our neighbors and friends.",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    audioUrl: "https://example.com/sermons/audio/reaching-lost.mp3",
    thumbnail: "/sermon-thumb-5.png",
    speakerPhoto: "/youth-leader-1.jpg",
    speakerBio: "Youth Pastor with a heart for mentoring young people in their spiritual journey.",
    views: 890,
    ministry: "Community Outreach",
    ministrySlug: "community-outreach",
  },
  6: {
    id: 6,
    title: "Building Character Like Christ",
    preacher: "Pastor Ian Sendegeya",
    date: "2023-12-09",
    duration: "47 min",
    category: "youth-services",
    series: "Youth Empowerment",
    description: "How young people can develop Christ-like character in a challenging world.",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    audioUrl: "https://example.com/sermons/audio/building-character.mp3",
    thumbnail: "/sermon-thumb-6.png",
    speakerPhoto: "/pastor-ian-sendegeya.jpg",
    speakerBio:
      "Lead Pastor at Seventh-day Adventist Church Masaka Town, passionate about youth ministry and evangelism.",
    views: 1120,
    ministry: "Youth Ministry",
    ministrySlug: "youth-ministry",
  },
}

export const seriesData = {
  "living-by-faith": {
    name: "Living by Faith",
    slug: "living-by-faith",
    description:
      "A powerful sermon series exploring what it means to walk by faith in our daily lives. Discover how to trust God completely, even when circumstances seem impossible, and learn practical ways to strengthen your faith journey.",
    sermons: [1, 4],
    thumbnail: "/series-living-by-faith.jpg",
  },
  "youth-empowerment": {
    name: "Youth Empowerment",
    slug: "youth-empowerment",
    description:
      "An inspiring series designed specifically for young people, addressing the unique challenges they face and equipping them with biblical principles for success. Learn how to develop godly character, make wise decisions, and become the leaders God has called you to be.",
    sermons: [2, 6],
    thumbnail: "/series-youth-empowerment.jpg",
  },
  "end-time-prophecy": {
    name: "End Time Prophecy",
    slug: "end-time-prophecy",
    description:
      "A comprehensive study of biblical prophecy and end-time events. Understand the signs of the times, the Three Angels' Messages, and how to prepare spiritually for Christ's soon return. This series provides clarity and hope in uncertain times.",
    sermons: [3],
    thumbnail: "/series-end-time-prophecy.jpg",
  },
  "mission-outreach": {
    name: "Mission Outreach",
    slug: "mission-outreach",
    description:
      "Discover your role in God's mission to reach the world with the gospel. This series provides practical strategies for evangelism, community service, and sharing your faith effectively. Learn how to be Christ's hands and feet in your neighborhood and beyond.",
    sermons: [5],
    thumbnail: "/series-mission-outreach.jpg",
  },
}
